#!/bin/bash
# -*- mode: bash; tab-size: 4; -*-
# setup-locale.sh — Set system locale
#
# Usage:
#   setup-locale.sh [locale]    # e.g. en_US.UTF-8, zh_TW.UTF-8
#   setup-locale.sh             # interactive mode

set -Eeuo pipefail

SCRIPT_NAME="$(basename "${BASH_SOURCE[0]}" .sh)"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LIB_DIR="${SCRIPT_DIR}/../../lib"

for lib in "${LIB_DIR}"/*.sh; do
    [[ -f "${lib}" ]] && source "${lib}"
done

require_root

DEFAULT_LOCALE="en_US.UTF-8"
LOCALE_FILE="/etc/locale.gen"
LOCALE_GEN="/etc/default/locale"

list_locales() {
    grep -E "^#?.*UTF-8" "${LOCALE_FILE}" 2>/dev/null | sed 's/^#//; s/[[:space:]]*//' | sort | uniq
}

do_setup() {
    local locale="$1"

    if ! grep -qE "^#?[[:space:]]*${locale}" "${LOCALE_FILE}" 2>/dev/null; then
        log_error "Locale ${locale} is not found in ${LOCALE_FILE}."
        return 1
    fi

    log_info "Generating locale ${locale}..."
    sed -i "s/^#[[:space:]]*\(${locale}\)/\1/" "${LOCALE_FILE}"
    locale-gen "${locale}" >/dev/null 2>&1

    log_info "Setting system default locale..."
    cat >"${LOCALE_GEN}" <<EOF
# This file is generated by linux-configs-and-scripts toolkit
LANG=${locale}
LANGUAGE=${locale%%.*}
EOF

    update-locale LANG="${locale}" LANGUAGE="${locale%%.*}" 2>/dev/null || true

    log_success "Locale successfully set to ${locale}."
    log_warn "Please log out and back in for changes to take full effect."
}

main() {
    local locale=""
    local skip_confirm=false

    while getopts "y" opt; do
        case $opt in
        y) skip_confirm=true ;;
        *) ;;
        esac
    done
    shift $((OPTIND - 1))

    if [[ -n "${1:-}" ]]; then
        locale="$1"
    else
        log_info "Available UTF-8 locales on this system:"
        list_locales | column -c 80 | sed 's/^/  /'
        echo
        read -rp "Enter locale [${DEFAULT_LOCALE}]: " locale </dev/tty
        [[ -z "${locale}" ]] && locale="${DEFAULT_LOCALE}"
    fi

    if ! [[ "${locale}" =~ ^.+@?\.?[A-Za-z0-9_]+$ ]]; then
        log_error "Invalid locale format: ${locale}"
        return 1
    fi

    log_info "Current system LANG: ${LANG:-not set}"

    if [ "$skip_confirm" = false ]; then
        confirm "Set locale to ${locale}?" --default=yes || exit 0
    else
        log_info "Automatic mode: skipping confirmation."
    fi

    do_setup "${locale}"
}

main "$@"
