#!/bin/bash
# -*- mode: bash; tab-size: 4; -*-
# setup-locale.sh — Set system locale
#
# Usage:
#   setup-locale.sh [locale]    # e.g. en_US.UTF-8, zh_TW.UTF-8
#   setup-locale.sh             # interactive mode

set -Eeuo pipefail

SCRIPT_NAME="$(basename "${BASH_SOURCE[0]}" .sh)"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LIB_DIR="${SCRIPT_DIR}/../../lib"

for lib in "${LIB_DIR}"/*.sh; do
    [[ -f "${lib}" ]] && source "${lib}"
done

require_root

DEFAULT_LOCALE="en_US.UTF-8"
LOCALE_FILE="/etc/locale.gen"
LOCALE_GEN="/etc/default/locale"

list_locales() {
    grep -E "^[^#].*UTF-8" "${LOCALE_FILE}" 2>/dev/null | sed 's/:.*//' | sort
}

do_setup() {
    local locale="$1"

    if ! grep -q "^${locale}" "${LOCALE_FILE}" 2>/dev/null; then
        log_error "Locale ${locale} is not available in ${LOCALE_FILE}."
        log_info "Available UTF-8 locales:"
        list_locales | column -c 80 | sed 's/^/  /'
        return 1
    fi

    log_info "Generating locale ${locale}..."
    sed -i "s/^# \(${locale}\)/\1/" "${LOCALE_FILE}"
    locale-gen "${locale}" >/dev/null 2>&1

    log_info "Setting system default locale..."
    cat >"${LOCALE_GEN}" <<EOF
# This file is generated by linux-configs-and-scripts toolkit
LANG=${locale}
LANGUAGE=${locale%%.*}
EOF

    update-locale LANG="${locale}" LANGUAGE="${locale%%.*}" 2>/dev/null || true

    log_success "Locale set to ${locale}."
    log_warn "Log out and back in for changes to take full effect."
    log_info "Current locale: $(locale LANG)"
}

main() {
    local locale=""

    if [[ $# -gt 0 ]] && [[ -n "$1" ]]; then
        locale="$1"
    else
        log_info "Available UTF-8 locales on this system:"
        list_locales | column -c 80 | sed 's/^/  /'
        echo
        read -rp "Enter locale [${DEFAULT_LOCALE}]: " locale </dev/tty
        [[ -z "${locale}" ]] && locale="${DEFAULT_LOCALE}"
    fi

    if ! [[ "${locale}" =~ ^.+@?\.?[A-Za-z0-9_]+$ ]]; then
        log_error "Invalid locale: ${locale}"
        return 1
    fi

    log_info "Current locale: $(locale LANG 2>/dev/null || echo 'not set')"
    confirm "Set locale to ${locale}?" --default=yes || exit 0

    do_setup "${locale}"
}

main "$@"
