#!/usr/bin/env bash
# Configure the system default locale on Debian/Ubuntu.

set -euo pipefail

# shellcheck disable=SC1091
source "$(cd -P -- "$(dirname -- "${BASH_SOURCE[0]}")/../.." && pwd)/libs/common.sh"

DEFAULT_LOCALE="en_US.UTF-8"
LOCALE_FILE="/etc/locale.gen"
LOCALE_GEN="/etc/default/locale"
force=false
locale=""

list_locales() {
    require_file "${LOCALE_FILE}" || return 1

    awk '
        /^[[:space:]]*#?[[:space:]]*[^#[:space:]]+[[:space:]]+UTF-8/ {
            sub(/^[[:space:]]*#[[:space:]]*/, "")
            print $1
        }
    ' "${LOCALE_FILE}" | sort -u
}

locale_exists() {
    list_locales | grep -Fx -- "$1" >/dev/null
}

enable_locale() {
    local target_locale="$1"
    local tmp
    tmp="$(mktemp)"

    awk -v locale="${target_locale}" '
        {
            line = $0
            uncommented = line
            sub(/^[[:space:]]*#[[:space:]]*/, "", uncommented)
            split(uncommented, fields, /[[:space:]]+/)
            print (fields[1] == locale) ? uncommented : line
        }
    ' "${LOCALE_FILE}" >"${tmp}"

    cat "${tmp}" >"${LOCALE_FILE}"
    rm -f "${tmp}"
}

prompt_locale() {
    local selected_locale=""

    {
        log_info "Available UTF-8 locales on this system:"
        if command_exists column; then
            list_locales | column -c 80 | sed 's/^/  /'
        else
            list_locales | sed 's/^/  /'
        fi

        echo
    } >&2

    if [[ -r /dev/tty ]]; then
        printf 'Enter locale [%s]: ' "${DEFAULT_LOCALE}" >/dev/tty
        read -r selected_locale </dev/tty || selected_locale=""
    else
        log_warn "No interactive terminal; using default locale: ${DEFAULT_LOCALE}"
        selected_locale="${DEFAULT_LOCALE}"
    fi

    printf '%s\n' "${selected_locale:-${DEFAULT_LOCALE}}"
}

while (($# > 0)); do
    case "$1" in
    -f)
        force=true
        shift
        ;;
    -*)
        log_error "Unknown option: $1"
        exit 1
        ;;
    *)
        if [[ -n "${locale}" ]]; then
            log_error "Unexpected extra argument: $1"
            exit 1
        fi
        locale="$1"
        shift
        ;;
    esac
done

require_root
require_cmd grep locale-gen

[[ -n "${locale}" ]] || locale="$(prompt_locale)"

if ! locale_exists "${locale}"; then
    log_error "Locale ${locale} is not available in ${LOCALE_FILE}."
    exit 1
fi

log_info "Current system LANG: ${LANG:-not set}"
if [[ "${force}" == false ]]; then
    confirm "Set locale to ${locale}?" --default=yes || exit 0
else
    log_info "Force mode: skipping confirmation."
fi

log_info "Generating locale ${locale}..."
enable_locale "${locale}"
locale-gen "${locale}" >/dev/null

log_info "Setting system default locale..."
cat >"${LOCALE_GEN}" <<EOF_LOCALE
# Generated by linux-configs-and-scripts toolkit
LANG=${locale}
LANGUAGE=${locale%%.*}
EOF_LOCALE

update-locale LANG="${locale}" LANGUAGE="${locale%%.*}" 2>/dev/null || true

log_success "Locale successfully set to ${locale}."
log_warn "Please log out and back in for changes to take full effect."
