# Listens
listen 443 quic;
listen 443 ssl;

# Headers
include public/headers/hsts-quic.conf;

set ssl_domain "";
ssl_certificate "certs/$ssl_domain/ecc/fullchain.pem";
ssl_certificate_key "certs/$ssl_domain/ecc/private.key";
ssl_trusted_certificate "certs/$ssl_domain/ecc/chain.pem";
