name: services

services:
  mongodb-main:
    container_name: mongodb-main
    image: mongodb/mongodb-community-server:latest
    ports:
      - 0.0.0.0:27017:27017
    restart: always
    user: root:nogroup
    volumes:
      - mongodb-main-config:/data/configdb
      - /data/databases/mongodb/main:/data/db

  portainer:
    container_name: portainer
    image: portainer/portainer-ce:alpine-sts
    ports:
      - 127.0.0.1:9000:9000
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data

volumes:
  mongodb-main-config:
  portainer-data:
