#!/bin/bash

echo -e 'Here is your cat.\n'
echo '            A____A    '
echo '           /*    *\   '
echo '          {   _  _ }  '
echo '          A` >  v /<  '
echo '        / !!!!! !!}   '
echo '       / ! \!!!!! |   '
echo '  ____{   ) |  |  |   '
echo ' / ___{ !!c |  |  |   '
echo '{ (___ \__\__@@_)@_)  '
echo ' \____)               '
echo 'Paradise is no longer paradise if there is no cat.'
