#!/bin/bash

set -e
exec >/dev/null

npm upgrade -g
corepack disable pnpm
corepack disable yarn
npm i -g \
    bun@latest \
    eslint@latest \
    npm@latest \
    pnpm@latest \
    yarn@latest

npm cache clean -g --force
